version: '3.5'

services:

    # app
    app:
        container_name: tcc-app
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: tcc-app-image
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
        expose:
            - "9000"
        networks:
            - laravel

    # nginx
    nginx:
        container_name: tcc-nginx
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/dev/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - laravel

    # database
    mariadb:
        container_name: tcc-mariadb
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    # adminer
    adminer:
        container_name: tcc-adminer
        image: adminer:latest
        networks:
            - laravel
        ports:
            - "8081:8081"

    # redis
    redis:
        container_name: tcc-redis
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
